site_name: Hello World
site_description: This page was created by mkdocs
site_author: "Nick"
site_url: https://nicholas-raspino.github.io/doc-test-submodule/
repo_name: doc-test-submodule
repo_url: https://github.com/nicholas-raspino/doc-test-submodule
# EDIT LINES ABOVE THIS ONE FOR A NEW REPOSITORY
edit_uri: "edit/main/docs/"
docs_dir: docs
site_dir: site
remote_branch: gh-pages

plugins:
  - search
  - awesome-nav
  - macros
  - git-revision-date-localized
  - git-authors
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold

theme:
  name: material
  custom_dir: docs/assets/overrides
  language: en
  features:
    - search.highlight
    - search.share
    - content.code.annotate
    - navigation.top
    - navigation.indexes
    - content.action.edit
  palette:
    - scheme: elastic-engineering-light
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  logo: "https://c0e9a73362c5d06f19d6-b39ff74cb91d713ac1253c5ae00eaccb.ssl.cf1.rackcdn.com/UI/logos/PNG/Rackspace_Icon_wt.png"
  favicon: "https://c0e9a73362c5d06f19d6-b39ff74cb91d713ac1253c5ae00eaccb.ssl.cf1.rackcdn.com/UI/favicon/favicon.ico"
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    admonition:
      quote: material/code-tags

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - meta
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: [".", "../"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true
