name: build and push live docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.DOCS_SITE_GET_TOKEN_APP_ID }}
          private-key: ${{ secrets.DOCS_SITE_GET_TOKEN_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up python
        uses: actions/setup-python@v5
        id: setuppythonstep
        with:
          python-version-file: ".python-version"
          check-latest: true
          cache: pip
          cache-dependency-path: "requirements.txt"
      - run: echo '${{ steps.setuppythonstep.outputs.python-version }}'
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy -f mkdocs.yml --force
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          # token: ${{ secrets.NICH1370_PAT}}
          token: ${{ steps.app-token.outputs.token }}
          repository: nicholas-raspino/doc-test-parent
          event-type: client-submodule-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repo": "${{ github.repository }}"}'