name: build and push live docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up python
        uses: actions/setup-python@v5
        id: setuppythonstep
        with:
          python-version-file: ".python-version"
          check-latest: true
          cache: pip
          cache-dependency-path: "requirements.txt"
      - run: echo '${{ steps.setuppythonstep.outputs.python-version }}'
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy -f mkdocs.yml --force
